version: "3"
# # INFO
# All $VARIABLES are currently stored in a .env file on the same level as this
# document, please remember to populate it.
#
# You can test to see if the variables are loading correctly with the command:
# * `docker compose config`
# If the variables still have a $ on them then the .env is not being loaded.

# # USAGE
# The reccomended commands when working with docker compose is to use:
# * `docker compose up --build`
# This will force any container with changes to rebuild
#
# The reccomended way to take down the containers is with:
# * `docker compose down -v`
# This will ensure that the volume is deleted too.

# ---------------------------------
# ------------ GATEWAY ------------
services:
  gateway: # NGINX
    container_name: gateway
    build:
      context: .
      dockerfile: ./configs/gateway/gateway.dockerfile
    networks: [docker-net]
    ports:
      - 80:80 # http
      - 3000:3000 # SFTP server
      # - 443:443
    restart: always

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    # environment:
    #   - RABBITMQ_DEFAULT_USER=$RABBITMQ_DEFAULT_USER
    #   - RABBITMQ_DEFAULT_PASS=$RABBITMQ_DEFAULT_PASS
    ports:
      - 5672:5672
      - 8080:15672
    networks: [docker-net]

  sftp-server:
    container_name: sftp-server
    build:
      context: .
      dockerfile: ./configs/atmoz-sftp/atmoz-sftp.dockerfile
    environment:
      - SFTP_USERNAME=$SFTP_USERNAME
    networks: [docker-net]
    #ports: # only open ports for direct container testing, let gateway reroute otherwise
    #  - 22:22
    volumes:
      - ftp-uploads:/home/$SFTP_USERNAME/upload
    command: "$SFTP_USERNAME:$SFTP_PASSWORD:1001"

  user-service:
    container_name: user-service
    build:
      context: .
      dockerfile: ./configs/user-service/user-service.dockerfile
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    networks: [docker-net, user-service-net]
    depends_on:
      - user-service-db

  user-service-db:
    container_name: user-service-db
    image: postgres:alpine # docs: https://github.com/docker-library/docs/blob/master/postgres/README.md
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    networks: [user-service-net]

# ---------------------------------
# ------------ NETWORK ------------
networks:
  docker-net:
    name: docker-net
  user-service-net:
    name: user-service-net

# ---------------------------------
# ------------ VOLUMES ------------
volumes:
  ftp-uploads:
    name: ftp-uploads
